### ISSUE TITLE
issue with hamburger/navbar

### ISSUE THREAD

**Issue by Angelbold** [Briank95/RestorativeJustice#1]
I screwed the navbar up and don't know how to restore with hamburger and icon in tact

**Comment by Angelbold** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="styles.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Alfa+Slab+One|Lato" rel="stylesheet">
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <title>Restorative Project</title>
</head>
<body>



<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
    </div>

    
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarTogglerDemo02">
      <div class="topnav-right">
        <ul class="navbar-nav mr-auto mt-2 mt-lg- ">
          <li class="nav-item"><a class="nav-link" href="restoration.html">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="about.html">About</a></li>
          <li class="nav-item"><a class="nav-link" href="blog.html">Blog</a></li>
          <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
        </ul>
      </div>
      <a class="nav-link" href="restoration.html"><img src = "images/restorProjLogo.png"></a></li>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button></div> 
      
      
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" >
        <button= my-2 my-sm-0><img src = "images/search.png" height="30px"></button>
      </form>
    </div>
  </div>
</nav>
      
              
    



    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">Restorative Justice</h1>
        <p class="lead">Change the World Starting with You</p>
      </div>
    </div>




     <div class="container">
      <div class="row align-items-start">
        <div class="col">
          <a href="about.html">
            <h4>Why Restorative Justice?</h4>
          <img src="./images/Originals/sitting.JPG" alt="mother sitting with her child" class="img-thumbnail">
          <div><br>
            <p class="description">
              <strong>Restorative justice </strong> repairs the harm caused by crime. When victims, offenders and community members meet to decide how to do that, the results can be transformational.
            </p></a>
          </div>
        </div>
        
        <div class="col">
          <a href="blog.html">
          <h4>Our Voices</h4>
          <img src="./images/Originals/talking.JPG" alt="two friends in discussion" class="img-thumbnail">
          <div><br>
            <p class="description">
              The name of the blog is RJOB, the acronym for Restorative Justice Online Blog. It is pronounced "Our Job" to remind us that it is up to us to develop, expand, evaluate and strengthen restorative justice theory and practice.
            </p></a>
          </div>
 
        </div>
        <div class="col">
          <a href="blog.html">
            <h4>Connect With Us</h4>
          <img src="./images/Unsplash/man.jpg" alt="computer" class="img-thumbnail">
          <div><br>
            <p class="description">
              If you would like to submit a short article or book review concerning restorative justice as a proposed blog entry, click here to contact us. 
            </p></a>
          </div>
 
        </div>
      </div>
    </div>   


<div id="header" class="text-white font-chunky five" >
 <h5 class="card-title">Be A Part Of The Movement</h5>
 <p class="card-text">Share the message of Restorative Justice and become an active community member.</p>
 <a href="about.html" class="btn btn-primary">Community Opportunities</a>
</div>



    <footer>
      <div class="container-fluid padding">
        <div class="row text-center">
         <div class="col-md-4">
         </div>
         <div class="col-md-12">
           <hr class="dark">
           <p>Restorative Justice &copy; YWeb Career Academy Inc. 2018</p>
         </div>
         </div>
   </footer>

  </body>
</html>

**Comment by toost19** [comment]
No worries! I’ll see what I can do  with it 😊

**Comment by Angelbold** [comment]
care pow got it ! love this girl! closing "issue" lol
